### ISSUE TITLE
home的banner没有完善

### ISSUE THREAD

**Issue by woshishulai** [Shmilysw/vue3-rabbit#2]
不能实现跳转 并样式有问题

**Comment by Shmilysw** [comment]
#### 修复问题
+ 有些是banner是本来黑马就没有的写的，这个看自己的是否想完善
+ 更新登录的账号和密码，我在代码里面也写了些账号密码，在Login index.vue 里面
+ 支付宝沙箱 在页面 Pay 下面的 index.vue 里面
  - 账号：askgxl8276@sandbox.com
  - 密码：111111
  - 支付密码：111111
